#pragma once

#include <QAbstractAnimation>
#include <QAbstractEventDispatcher>
#include <QAbstractItemModel>
#include <QAbstractListModel>
#include <QAbstractNativeEventFilter>
#include <QAbstractProxyModel>
#include <QAbstractState>
#include <QAbstractTableModel>
#include <QAbstractTransition>
#include <QAnimationDriver>
#include <QAnimationGroup>
#include <QArgument>
#include <QArrayData>
#include <QArrayDataPointer>
#include <QArrayDataPointerRef>
#include <QAssociativeIterable>
#include <QAtomicInt>
#include <QAtomicInteger>
#include <QAtomicPointer>
#include <QBasicMutex>
#include <QBasicTimer>
#include <QBEInteger>
#include <QBigEndianStorageType>
#include <QBitArray>
#include <QBitRef>
#include <QBuffer>
#include <QByteArray>
#include <QByteArrayData>
#include <QByteArrayDataPtr>
#include <QByteArrayList>
#include <QByteArrayListIterator>
#include <QByteArrayMatcher>
#include <QByteRef>
#include <QCache>
#include <QCalendar>
#include <QCborArray>
#include <QCborError>
#include <QCborMap>
#include <QCborParserError>
#include <QCborStreamReader>
#include <QCborStreamWriter>
#include <QCborValue>
#include <QCborValueRef>
#include <QChar>
#include <QCharRef>
#include <QChildEvent>
#include <QCollator>
#include <QCollatorSortKey>
#include <QCommandLineOption>
#include <QCommandLineParser>
#include <QConcatenateTablesProxyModel>
#include <QConstOverload>
#include <QContiguousCache>
#include <QContiguousCacheData>
#include <QContiguousCacheTypedData>
#include <QCoreApplication>
#include <QCryptographicHash>
#include <QDataStream>
#include <QDate>
#include <QDateTime>
#include <QDeadlineTimer>
#include <QDebug>
#include <QDebugStateSaver>
#include <QDeferredDeleteEvent>
#include <QDir>
#include <QDirIterator>
#include <QDynamicPropertyChangeEvent>
#include <QEasingCurve>
#include <QElapsedTimer>
#include <QEnableSharedFromThis>
#include <QEvent>
#include <QEventLoop>
#include <QEventLoopLocker>
#include <QEventTransition>
#include <QException>
#include <QExplicitlySharedDataPointer>
#include <QFactoryInterface>
#include <QFile>
#include <QFileDevice>
#include <QFileInfo>
#include <QFileInfoList>
#include <QFileSelector>
#include <QFileSystemWatcher>
#include <QFinalState>
#include <QFlag>
#include <QFlags>
#include <QFloat16>
#include <QFunctionPointer>
#include <QFuture>
#include <QFutureInterface>
#include <QFutureInterfaceBase>
#include <QFutureIterator>
#include <QFutureSynchronizer>
#include <QFutureWatcher>
#include <QFutureWatcherBase>
#include <QGenericArgument>
#include <QGenericReturnArgument>
#include <QGlobalStatic>
#include <QHash>
#include <QHashData>
#include <QHashDummyValue>
#include <QHashFunctions>
#include <QHashIterator>
#include <QHashNode>
#include <QHistoryState>
#include <QIdentityProxyModel>
#include <QIncompatibleFlag>
#include <QIntegerForSize>
#include <QInternal>
#include <QIODevice>
#include <QItemSelection>
#include <QItemSelectionModel>
#include <QItemSelectionRange>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QJsonValue>
#include <QJsonValuePtr>
#include <QJsonValueRef>
#include <QJsonValueRefPtr>
#include <QKeyValueIterator>
#include <QLatin1Char>
#include <QLatin1Literal>
#include <QLatin1String>
#include <QLEInteger>
#include <QLibrary>
#include <QLibraryInfo>
#include <QLine>
#include <QLineF>
#include <QLinkedList>
#include <QLinkedListData>
#include <QLinkedListIterator>
#include <QLinkedListNode>
#include <QList>
#include <QListData>
#include <QListIterator>
#include <QListSpecialMethods>
#include <QLittleEndianStorageType>
#include <QLocale>
#include <QLockFile>
#include <QLoggingCategory>
#include <QMap>
#include <QMapData>
#include <QMapDataBase>
#include <QMapIterator>
#include <QMapNode>
#include <QMapNodeBase>
#include <QMargins>
#include <QMarginsF>
#include <QMessageAuthenticationCode>
#include <QMessageLogContext>
#include <QMessageLogger>
#include <QMetaClassInfo>
#include <QMetaEnum>
#include <QMetaMethod>
#include <QMetaObject>
#include <QMetaProperty>
#include <QMetaType>
#include <QMimeData>
#include <QMimeDatabase>
#include <QMimeType>
#include <QModelIndex>
#include <QModelIndexList>
#include <QMultiHash>
#include <QMultiMap>
#include <QMutableByteArrayListIterator>
#include <QMutableFutureIterator>
#include <QMutableHashIterator>
#include <QMutableLinkedListIterator>
#include <QMutableListIterator>
#include <QMutableMapIterator>
#include <QMutableSetIterator>
#include <QMutableStringListIterator>
#include <QMutableVectorIterator>
#include <QMutex>
#include <QMutexLocker>
#include <QNoDebug>
#include <QNonConstOverload>
#include <QObject>
#include <QObjectCleanupHandler>
#include <QObjectData>
#include <QObjectList>
#include <QObjectUserData>
#include <QOperatingSystemVersion>
#include <QPair>
#include <QParallelAnimationGroup>
#include <QPauseAnimation>
#include <QPersistentModelIndex>
#include <QPluginLoader>
#include <QPluginMetaData>
#include <QPoint>
#include <QPointer>
#include <QPointF>
#include <QProcess>
#include <QProcessEnvironment>
#include <QPropertyAnimation>
#include <QQueue>
#include <QRandomGenerator>
#include <QRandomGenerator64>
#include <QReadLocker>
#include <QReadWriteLock>
#include <QRect>
#include <QRectF>
#include <QRecursiveMutex>
#include <QRegExp>
#include <QRegularExpression>
#include <QRegularExpressionMatch>
#include <QRegularExpressionMatchIterator>
#include <QResource>
#include <QReturnArgument>
#include <QRunnable>
#include <QSaveFile>
#include <QScopedArrayPointer>
#include <QScopedPointer>
#include <QScopedPointerArrayDeleter>
#include <QScopedPointerDeleteLater>
#include <QScopedPointerDeleter>
#include <QScopedPointerObjectDeleteLater>
#include <QScopedPointerPodDeleter>
#include <QScopedValueRollback>
#include <QScopeGuard>
#include <QSemaphore>
#include <QSemaphoreReleaser>
#include <QSequentialAnimationGroup>
#include <QSequentialIterable>
#include <QSet>
#include <QSetIterator>
#include <QSettings>
#include <QSharedData>
#include <QSharedDataPointer>
#include <QSharedMemory>
#include <QSharedPointer>
#include <QSignalBlocker>
#include <QSignalMapper>
#include <QSignalTransition>
#include <QSize>
#include <QSizeF>
#include <QSocketDescriptor>
#include <QSocketNotifier>
#include <QSortFilterProxyModel>
#include <QSpecialInteger>
#include <QStack>
#include <QStandardPaths>
#include <QState>
#include <QStateMachine>
#include <QStaticArrayData>
#include <QStaticByteArrayData>
#include <QStaticByteArrayMatcherBase>
#include <QStaticPlugin>
#include <QStaticStringData>
#include <QStorageInfo>
#include <QString>
#include <QStringAlgorithms>
#include <QStringBuilder>
#include <QStringData>
#include <QStringDataPtr>
#include <QStringList>
#include <QStringListIterator>
#include <QStringListModel>
#include <QStringLiteral>
#include <QStringMatcher>
#include <QStringRef>
#include <QStringView>
#include <QSysInfo>
#include <QSystemSemaphore>
#include <Qt>
#include <QtAlgorithms>
#include <QtCborCommon>
#include <QtCleanUpFunction>
#include <QtConfig>
#include <QtContainerFwd>
#include <QtCore>
#include <QtCoreDepends>
#include <QtCoreVersion>
#include <QtDebug>
#include <QTemporaryDir>
#include <QTemporaryFile>
#include <QtEndian>
#include <QTextBoundaryFinder>
#include <QTextCodec>
#include <QTextDecoder>
#include <QTextEncoder>
#include <QTextStream>
#include <QTextStreamFunction>
#include <QTextStreamManipulator>
#include <QtGlobal>
#include <QThread>
#include <QThreadPool>
#include <QThreadStorage>
#include <QThreadStorageData>
#include <QTime>
#include <QTimeLine>
#include <QTimer>
#include <QTimerEvent>
#include <QTimeZone>
#include <QtMath>
#include <QtMessageHandler>
#include <QtMsgHandler>
#include <QtNumeric>
#include <QtPlugin>
#include <QtPluginInstanceFunction>
#include <QtPluginMetaDataFunction>
#include <QTranslator>
#include <QTransposeProxyModel>
#include <QTypeInfo>
#include <QTypeInfoMerger>
#include <QTypeInfoQuery>
#include <QUnhandledException>
#include <QUrl>
#include <QUrlQuery>
#include <QUrlTwoFlags>
#include <QUuid>
#include <QVariant>
#include <QVariantAnimation>
#include <QVariantComparisonHelper>
#include <QVariantHash>
#include <QVariantList>
#include <QVariantMap>
#include <QVarLengthArray>
#include <QVector>
#include <QVectorIterator>
#include <QVersionNumber>
#include <QWaitCondition>
#include <QWeakPointer>
#include <QWinEventNotifier>
#include <QWriteLocker>
#include <QXmlStreamAttribute>
#include <QXmlStreamAttributes>
#include <QXmlStreamEntityDeclaration>
#include <QXmlStreamEntityDeclarations>
#include <QXmlStreamEntityResolver>
#include <QXmlStreamNamespaceDeclaration>
#include <QXmlStreamNamespaceDeclarations>
#include <QXmlStreamNotationDeclaration>
#include <QXmlStreamNotationDeclarations>
#include <QXmlStreamReader>
#include <QXmlStreamStringRef>
#include <QXmlStreamWriter>